### ISSUE TITLE
It looks like you addressed my problem that I have been working on with Assert

### ISSUE THREAD

**Issue by Guyverix** [simplesamlphp/assert#6]
However, I am still learning PHP and was hoping that you might have some example code to show how to catch the exceptions to map to other exception values.

**Comment by tvdijen** [comment]
Hi @Guyverix!  What exactly are you looking for?
The way how we catch the generic exception from `webmozarts/assert` and exchange it for a custom exception?

**Comment by tvdijen** [comment]
https://github.com/simplesamlphp/assert/blob/master/src/Assert.php#L323-L366

What we do is to basically override the interface of the assertion-methods, so they can take additional parameters. Then we closely look at the last parameter and test if it's a class implementing the `Throwable` interface. If so, we use that class as the exception to throw when the assertion fails.

Next step is to call the original webmozarts-assertion in a try-catch statement.. If an exception is thrown, we catch it, and instead throw the exception that was passed as the extra parameter.

**Comment by tvdijen** [comment]
Here I have stripped it down to the bare necessities for you;

```
<?php

namespace SimpleSAML\Assert;

use Webmozart\Assert\Assert as Webmozart;

final class Assert
{
    public static function __callStatic(string $name, array $arguments): void
    {
        // We default to an exception we have created ourselves.
        $exception = AssertionFailedException::class;

        // We parse the parameters passed; if the last one is an exception, use that later on
        $last = end($arguments);
        if (is_string($last) && class_exists($last) && is_subclass_of($last, \Throwable::class)) {
            $exception = $last;
            array_pop($arguments);
        }

        // Try calling Webmozarts method and catch any exceptions that may occur
        try {
            if (method_exists(Webmozart::class, $name)) {
                call_user_func_array([Webmozart::class, $name], $arguments);
                return;
            } else {
                throw new \BadMethodCallException(sprintf("Assertion named `%s` does not exists.", $name));
            }
        } catch (\InvalidArgumentException $e) {
            // We caught an exception during the call to Webmozarts methods -> throw a custom exception
            throw new $exception($e->getMessage());
        }
    }
```

**Comment by Guyverix** [comment]
Thank you!  it is much clearer now.   I think this is what I was hoping for.  Specifically the try catch, as I wanted to add my logging into the catch block when it throws the exception.  Normally, I was not able to get it to log in the catch block, but would within the try block.  Now I can actually get different HTTP response codes, which was frustrating for me as it would only return a 500 error..

**Comment by tvdijen** [comment]
Not sure what you mean with those response codes, but I'm glad I could help and clarify.
OK if I close this issue, or do you have more questions?

**Comment by Guyverix** [comment]
Grin, sorry got excited I have an end in sight :)..  Yes, pls feel free to close this out..

Thank you again

**Comment by tvdijen** [comment]
No worries. Feel free to get back to us if you need!
